import { promises as fs } from "fs";
import path from "path";
import { generateMetaFilesFromConsolidated } from "./generate-meta-from-consolidated";
import distill from "./distill";
import logger from "../lib/logger";

async function runFullGeneration() {
  const rootDir = process.cwd();

  // Define paths
  const finalDappsRewrittenPath = path.join(rootDir, "final_dapps.rewritten.json");
  const sourceAppsDir = path.join(rootDir, "src", "apps");
  const outputDataDir = path.join(rootDir, "build");
  const appsMinPath = path.join(outputDataDir, "apps.min.json");
  const facetsIndexPath = path.join(outputDataDir, "facets.index.json");

  try {
    logger.info("Starting full generation process...");

    // 1. Cleanup
    logger.info("Cleaning up previous generated files...");
    await fs.rm(sourceAppsDir, { recursive: true, force: true });
    await fs.rm(appsMinPath, { force: true });
    await fs.rm(facetsIndexPath, { force: true });
    await fs.mkdir(sourceAppsDir, { recursive: true }); // Recreate src/apps
    logger.info("Cleanup complete.");

    // 2. Generate individual meta.json files
    logger.info("Generating individual meta.json files...");
    // Note: generateMetaFilesFromConsolidated expects final_dapps.rewritten.json to exist.
    // If final_dapps.rewritten.json itself needs to be generated, that step
    // must be added here before calling generateMetaFilesFromConsolidated.
    // For now, assuming final_dapps.rewritten.json is either manually placed or generated by another process.
    await generateMetaFilesFromConsolidated(finalDappsRewrittenPath, sourceAppsDir);
    logger.info("Individual meta.json files generated.");

    // 3. Distill and generate facets
    logger.info("Starting distillation and facet generation...");
    await distill(sourceAppsDir, outputDataDir);
    logger.info("Distillation and facet generation complete.");

    logger.info("✓ Full generation process completed successfully.");
    process.exit(0);
  } catch (error) {
    logger.error({ error }, "✗ Full generation process failed with error.");
    console.error("\n=== FULL GENERATION ERROR ===");
    console.error(error);
    console.error("=========================\n");
    process.exit(1);
  }
}

// Call the main function
runFullGeneration();
